Added document about becoming maintainer
ByConity/byconity.github.io pull request #103
Opened 2023-04-07 14:31 UTC by WillemJiang

Fix #97

2023-04-17 12:24 UTC, Adora627 requested changes
The whole doc looks duplicated twice. Could you refine it into one piece?

2023-04-18 03:54 UTC, WillemJiang commented
> The whole doc looks duplicated twice. Could you refine it into one piece?

Sorry, I forgot to clean up the old part before updating the rewrite version.

2023-05-22 00:40 UTC, Adora627 approved these changes

2023-05-22 00:41 UTC, Adora627 approved these changes

2023-05-22 01:29 UTC, merged