create a new doc about bucket table practice guide
ByConity/byconity.github.io pull request #81
Opened 2023-03-27 06:56 UTC by Adora627

note: didn't contain the bucket design doc which may relate to

2023-03-27 07:25 UTC, WillemJiang commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +2. 针对 cluster key 的聚合计算，可以有更少的内存占用和更短的执行时间，配合 distributed_perfect_shard 优化可以获得进一步的提高
建议给出 distributed_perfect_shard 使用说明的链接

2023-03-27 07:33 UTC, WillemJiang requested changes

2023-03-27 07:33 UTC, WillemJiang commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +1. distinct 值需要至少超过 worker 数量
能解释一下这一要求背后的原因吗？

2023-03-27 07:33 UTC, WillemJiang commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +2. 如果 distinct 值数量较小，最好能保持 worker 数量的倍数，以实现查询时数据分布的更均衡
建议给出具体的示例方便用户的理解。

2023-03-27 07:33 UTC, WillemJiang commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +这里有两种情况：
”这里有两种情况 “ 说得不是很清楚，  建议结合上下文重新描述一下。

2023-03-29 08:12 UTC, janplus commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +2. 针对 cluster key 的聚合计算，可以有更少的内存占用和更短的执行时间，配合 distributed_perfect_shard 优化可以获得进一步的提高
我后面补充一下，可以理解为在开源的 `distributed_group_by_no_merge` 上的改进

2023-03-29 08:13 UTC, janplus commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +1. distinct 值需要至少超过 worker 数量
因为相同的 cluster key 的行会发送到同一个 worker 上进行计算，因此如果 distinct 值小于 worker 数量则无法利用全部的worker进行 scan 计算

2023-03-29 08:14 UTC, janplus commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +2. 如果 distinct 值数量较小，最好能保持 worker 数量的倍数，以实现查询时数据分布的更均衡
相应的用例我后面也补充下

2023-03-29 08:15 UTC, janplus commented on docs/高级用户手册/Bucket Table 最佳实践.mdx
> +这里有两种情况：
OK，这里指的是 `两种修改 cluster by 定义的情况`

2023-04-01 00:56 UTC, WillemJiang commented
@janplus  
Can you edit the documentation directly in this PR?
If not how about we merge the doc first, then create another PR to polish the document?

2023-04-03 06:41 UTC, WillemJiang approved these changes
Merged the document first， @janplus will polish it later.

2023-04-03 06:41 UTC, merged